<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    // Valid categories: Sweets, Namkeen, Desi Ghee, Cookies, Mathi, Dry Fruits, Syrup.

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Kesar Rabri',
                'category' => 'Sweets',
                'description' => 'Slow-simmered full-cream milk, reduced for hours and finished with saffron, pistachio and rose. Served chilled in a clay kulhad.',
                'price' => 150,
                'weight' => '1 Bowl',
                'tag' => 'Chilled',
                'image' => 'images/products/rabri.jpg',
                'color' => '#c8962e',
                'sort_order' => 1,
            ],
            [
                'name' => 'Kaju Katli',
                'category' => 'Sweets',
                'description' => 'Pure cashew and sugar, hand-rolled wafer-thin and dusted with real silver warq. Our most-gifted mithai, festival after festival.',
                'price' => 450,
                'weight' => '250g',
                'tag' => 'Silver Warq',
                'image' => 'images/products/kaju-katli.jpg',
                'color' => '#7a1622',
                'sort_order' => 2,
            ],
            [
                'name' => 'Kesar Milk Cake',
                'category' => 'Sweets',
                'description' => 'Soft-grained milk fudge simmered with saffron strands and finished with almond slivers. Melts the moment it hits your tongue.',
                'price' => 320,
                'weight' => '250g',
                'tag' => 'Saffron',
                'image' => 'images/products/milk-cake.jpg',
                'color' => '#c1440e',
                'sort_order' => 3,
            ],
            [
                'name' => 'Malai Rasgulla',
                'category' => 'Sweets',
                'description' => 'Spongy chhena balls soaked in light sugar syrup, topped with a whisper of pistachio. Soft, milky, and never too sweet.',
                'price' => 180,
                'weight' => '6 pcs',
                'tag' => 'Bestseller',
                'image' => 'images/products/rasgulla.jpg',
                'color' => '#3d7a52',
                'sort_order' => 4,
            ],
            [
                'name' => 'Anjeer Dry Fruit Roll',
                'category' => 'Dry Fruits',
                'description' => 'Fig and mixed dry fruits rolled thick and crusted in pistachio. No added sugar — just fruit, nuts and ghee.',
                'price' => 380,
                'weight' => '250g',
                'tag' => 'No Sugar Added',
                'image' => 'images/products/dryfruit-roll.jpg',
                'color' => '#6b4423',
                'sort_order' => 5,
            ],

            // Sweets
            [
                'name' => 'Motichoor Ladoo',
                'category' => 'Sweets',
                'description' => "Tiny fried gram-flour pearls, soaked in saffron syrup and pressed into soft, melt-in-mouth ladoos. A festival classic, made fresh daily.",
                'price' => 220, 'weight' => '250g', 'tag' => 'Festive Favourite',
                'image' => 'images/products/motichoor-ladoo.jpg', 'color' => '#c8962e', 'sort_order' => 6,
            ],
            [
                'name' => 'Gulab Jamun',
                'category' => 'Sweets',
                'description' => "Khoya dumplings deep-fried to a deep golden brown and soaked in rose-cardamom syrup. Served warm, they're softer than any you've had.",
                'price' => 200, 'weight' => '500g (12 pcs)', 'tag' => 'Soft & Syrupy',
                'image' => 'images/products/gulab-jamun.jpg', 'color' => '#7a1622', 'sort_order' => 7,
            ],
            [
                'name' => 'Besan Ladoo',
                'category' => 'Sweets',
                'description' => "Roasted gram flour, pure ghee and sugar, hand-rolled the old way. Nutty, crumbly, and never overly sweet.",
                'price' => 210, 'weight' => '250g', 'tag' => "Grandma's Recipe",
                'image' => 'images/products/besan-ladoo.jpg', 'color' => '#c1440e', 'sort_order' => 8,
            ],
            [
                'name' => 'Soan Papdi',
                'category' => 'Sweets',
                'description' => "Gram flour and sugar spun into delicate, flaky threads that melt the moment they touch your tongue. A festival gifting favourite.",
                'price' => 180, 'weight' => '400g', 'tag' => 'Flaky Layers',
                'image' => 'images/products/soan-papdi.jpg', 'color' => '#3d7a52', 'sort_order' => 9,
            ],
            [
                'name' => 'Mathura Peda',
                'category' => 'Sweets',
                'description' => "Khoya slow-cooked with sugar and cardamom until it turns a deep caramel brown — the classic peda straight from Mathura's sweet shops.",
                'price' => 260, 'weight' => '250g', 'tag' => 'Original Recipe',
                'image' => 'images/products/mathura-peda.jpg', 'color' => '#a97a1f', 'sort_order' => 10,
            ],
            [
                'name' => 'Kalakand',
                'category' => 'Sweets',
                'description' => "Grainy milk-solid fudge set soft and studded with pistachio. Rich, milky and not too sweet — a Makhanbhog household favourite.",
                'price' => 300, 'weight' => '300g', 'tag' => 'Milk Cake',
                'image' => 'images/products/kalakand.jpg', 'color' => '#8a1c2b', 'sort_order' => 11,
            ],
            [
                'name' => 'Cham Cham',
                'category' => 'Sweets',
                'description' => "Oval chhena dumplings soaked in light sugar syrup and finished with a dusting of khoya. Soft, spongy, and delicately sweet.",
                'price' => 190, 'weight' => '6 pcs', 'tag' => 'Bengali Sweet',
                'image' => 'images/products/cham-cham.jpg', 'color' => '#d4a940', 'sort_order' => 12,
            ],
            [
                'name' => 'Gujiya',
                'category' => 'Sweets',
                'description' => "Crisp pastry pockets stuffed with khoya, dry fruits and coconut, deep-fried till golden. A Holi and Diwali household must-have.",
                'price' => 220, 'weight' => '6 pcs', 'tag' => 'Seasonal Special',
                'image' => 'images/products/gujiya.jpg', 'color' => '#5c9468', 'sort_order' => 13,
            ],
            [
                'name' => 'Coconut Barfi',
                'category' => 'Sweets',
                'description' => "Fresh grated coconut cooked down with condensed milk and sugar into soft, chewy squares. Simple, fragrant, and always a hit.",
                'price' => 200, 'weight' => '250g', 'tag' => 'Fresh Coconut',
                'image' => 'images/products/coconut-barfi.jpg', 'color' => '#6b1420', 'sort_order' => 14,
            ],
            [
                'name' => 'Sandesh',
                'category' => 'Sweets',
                'description' => "Delicate chhena sweet, lightly sweetened and shaped by hand — a Bengali classic that lets the fresh milk flavour shine through.",
                'price' => 230, 'weight' => '6 pcs', 'tag' => 'Bengali Classic',
                'image' => 'images/products/sandesh.jpg', 'color' => '#4a0e17', 'sort_order' => 15,
            ],

            // Namkeen
            [
                'name' => 'Aloo Bhujia',
                'category' => 'Namkeen',
                'description' => "Fine potato and gram-flour sev, seasoned with a secret spice mix and fried till shatteringly crisp. Our best-selling teatime namkeen.",
                'price' => 90, 'weight' => '200g', 'tag' => 'Extra Crispy',
                'image' => 'images/products/aloo-bhujia.jpg', 'color' => '#c1440e', 'sort_order' => 16,
            ],
            [
                'name' => 'Moong Dal Namkeen',
                'category' => 'Namkeen',
                'description' => "Split moong dal, deep-fried and tossed with salt, chilli and a hint of black pepper. Light, crunchy, and hard to stop snacking on.",
                'price' => 100, 'weight' => '200g', 'tag' => 'Protein Rich',
                'image' => 'images/products/moong-dal-namkeen.jpg', 'color' => '#a97a1f', 'sort_order' => 17,
            ],
            [
                'name' => 'Khatta Meetha Mixture',
                'category' => 'Namkeen',
                'description' => "Our signature blend of sev, boondi, peanuts, and papdi tossed with a sweet-and-tangy masala. The ultimate all-day snack mix.",
                'price' => 110, 'weight' => '250g', 'tag' => 'Sweet & Tangy',
                'image' => 'images/products/khatta-meetha.jpg', 'color' => '#8a1c2b', 'sort_order' => 18,
            ],
            [
                'name' => 'Navratan Mixture',
                'category' => 'Namkeen',
                'description' => "Nine crunchy elements — sev, nuts, corn, boondi and more — combined into one richly spiced namkeen mix.",
                'price' => 120, 'weight' => '250g', 'tag' => 'Nine Treasures',
                'image' => 'images/products/masala-peanuts.jpg', 'color' => '#d4a940', 'sort_order' => 19,
            ],
            [
                'name' => 'Chana Jor Garam',
                'category' => 'Namkeen',
                'description' => "Flattened Bengal gram tossed with onion, chilli, lemon and chaat masala — the same tangy street-side namkeen, packed fresh for home.",
                'price' => 90, 'weight' => '200g', 'tag' => 'Street Style',
                'image' => 'images/products/chana-jor-garam.jpg', 'color' => '#7a1622', 'sort_order' => 20,
            ],
            [
                'name' => 'Ratlami Sev',
                'category' => 'Namkeen',
                'description' => "Thick, coarsely-ground gram-flour sev spiced with whole black pepper and fennel — a Ratlam classic, fried fresh in-house.",
                'price' => 100, 'weight' => '200g', 'tag' => 'Malwa Special',
                'image' => 'images/products/ratlami-sev.jpg', 'color' => '#c8962e', 'sort_order' => 21,
            ],
            [
                'name' => 'Dal Moth',
                'category' => 'Namkeen',
                'description' => "Crisp fried moth dal and peanuts tossed in a light spice mix. A humble, endlessly moreish everyday namkeen.",
                'price' => 95, 'weight' => '200g', 'tag' => 'Crunchy Classic',
                'image' => 'images/products/chana-jor-garam.jpg', 'color' => '#6b1420', 'sort_order' => 22,
            ],
            [
                'name' => 'Bhel Puri Mix',
                'category' => 'Namkeen',
                'description' => "Puffed rice, sev, and crunchy boondi — everything you need to make restaurant-style bhel at home in minutes.",
                'price' => 110, 'weight' => '250g', 'tag' => 'Chaat Ready',
                'image' => 'images/products/bhel-mix.jpg', 'color' => '#5c9468', 'sort_order' => 23,
            ],
            [
                'name' => 'Masala Peanuts',
                'category' => 'Namkeen',
                'description' => "Peanuts double-fried in a spiced gram-flour coating till deeply crunchy. Simple, addictive, and perfect with evening chai.",
                'price' => 85, 'weight' => '200g', 'tag' => 'Spiced & Fried',
                'image' => 'images/products/masala-peanuts.jpg', 'color' => '#3d7a52', 'sort_order' => 24,
            ],
            [
                'name' => 'Cornflakes Mixture',
                'category' => 'Namkeen',
                'description' => "Roasted cornflakes tossed with peanuts, curry leaves and a light masala — a lighter, crunchier take on classic chivda.",
                'price' => 105, 'weight' => '250g', 'tag' => 'Light & Crispy',
                'image' => 'images/products/cornflakes-chivda.jpg', 'color' => '#4a0e17', 'sort_order' => 25,
            ],

            // Desi Ghee
            [
                'name' => 'Cow Ghee',
                'category' => 'Desi Ghee',
                'description' => "Slow-simmered from fresh cow's milk using the traditional bilona method. Golden, aromatic, and perfect for tempering or a spoon over dal.",
                'price' => 450, 'weight' => '500ml', 'tag' => 'A2 Quality',
                'image' => 'images/products/ghee-tin.jpg', 'color' => '#d4a940', 'sort_order' => 26,
            ],
            [
                'name' => 'Buffalo Ghee',
                'category' => 'Desi Ghee',
                'description' => "Thick, richly-grained buffalo milk ghee with a deep, roasted aroma — the way most Indian kitchens remember ghee tasting.",
                'price' => 420, 'weight' => '500ml', 'tag' => 'Rich & Thick',
                'image' => 'images/products/buffalo-ghee.jpg', 'color' => '#c8962e', 'sort_order' => 27,
            ],
            [
                'name' => 'A2 Bilona Ghee',
                'category' => 'Desi Ghee',
                'description' => "Made the traditional bilona way — curd hand-churned, then slow-cooked over a wood fire. Nothing but pure, grainy ghee.",
                'price' => 550, 'weight' => '500ml', 'tag' => 'Hand-Churned',
                'image' => 'images/products/ghee-tin.jpg', 'color' => '#a97a1f', 'sort_order' => 28,
            ],
            [
                'name' => 'Herbal Ghee',
                'category' => 'Desi Ghee',
                'description' => "Cow ghee infused with a light Ayurvedic herb blend during cooking, for a subtly medicinal aroma alongside everyday cooking use.",
                'price' => 380, 'weight' => '250ml', 'tag' => 'Ayurvedic Blend',
                'image' => 'images/products/buffalo-ghee.jpg', 'color' => '#e9c873', 'sort_order' => 29,
            ],
            [
                'name' => 'Organic Ghee',
                'category' => 'Desi Ghee',
                'description' => "Made from the milk of grass-fed cows raised without chemical feed. Clean, pure, and unmistakably fragrant.",
                'price' => 500, 'weight' => '500ml', 'tag' => 'Certified Organic',
                'image' => 'images/products/ghee-tin.jpg', 'color' => '#c8962e', 'sort_order' => 30,
            ],
            [
                'name' => 'Vedic Ghee',
                'category' => 'Desi Ghee',
                'description' => "Prepared following age-old Vedic bilona techniques — slow, patient, and worth every extra hour it takes.",
                'price' => 480, 'weight' => '500ml', 'tag' => 'Ancient Method',
                'image' => 'images/products/buffalo-ghee.jpg', 'color' => '#a97a1f', 'sort_order' => 31,
            ],
            [
                'name' => 'Danedar Ghee',
                'category' => 'Desi Ghee',
                'description' => "Cooked just long enough to develop ghee's signature danedar (grainy) texture — the mark of a truly well-made batch.",
                'price' => 460, 'weight' => '500ml', 'tag' => 'Grainy Texture',
                'image' => 'images/products/ghee-tin.jpg', 'color' => '#d4a940', 'sort_order' => 32,
            ],
            [
                'name' => 'Kachi Ghani Ghee',
                'category' => 'Desi Ghee',
                'description' => "Made using slow, low-heat processing that preserves more of the milk's natural flavour and nutrients.",
                'price' => 440, 'weight' => '500ml', 'tag' => 'Cold Pressed Style',
                'image' => 'images/products/buffalo-ghee.jpg', 'color' => '#c8962e', 'sort_order' => 33,
            ],
            [
                'name' => 'Bilona Ghee 1kg',
                'category' => 'Desi Ghee',
                'description' => "Our best-selling bilona ghee in a larger jar for the whole family — same slow, traditional process, better value.",
                'price' => 850, 'weight' => '1kg', 'tag' => 'Family Pack',
                'image' => 'images/products/ghee-tin.jpg', 'color' => '#a97a1f', 'sort_order' => 34,
            ],
            [
                'name' => 'Premium Ghee Gift Jar',
                'category' => 'Desi Ghee',
                'description' => "Our finest ghee packed in a gift-ready jar — perfect for festivals, housewarmings, or as a thoughtful thank-you.",
                'price' => 520, 'weight' => '500ml', 'tag' => 'Gift Ready',
                'image' => 'images/products/buffalo-ghee.jpg', 'color' => '#d4a940', 'sort_order' => 35,
            ],

            // Cookies
            [
                'name' => 'Nankhatai',
                'category' => 'Cookies',
                'description' => "Crumbly, ghee-rich shortbread cookies flavoured with cardamom — an old-fashioned Indian bakery classic, eggless and always fresh.",
                'price' => 160, 'weight' => '250g', 'tag' => 'Eggless',
                'image' => 'images/products/nankhatai-2.jpg', 'color' => '#a97a1f', 'sort_order' => 36,
            ],
            [
                'name' => 'Butter Cookies',
                'category' => 'Cookies',
                'description' => "Rich, buttery cookies baked till golden at the edges. Simple, comforting, and impossible to stop at one.",
                'price' => 150, 'weight' => '200g', 'tag' => 'Melt in Mouth',
                'image' => 'images/products/butter-cookies.jpg', 'color' => '#6b4423', 'sort_order' => 37,
            ],
            [
                'name' => 'Jeera Cookies',
                'category' => 'Cookies',
                'description' => "Light, savoury biscuits studded with roasted cumin — a perfect not-too-sweet companion to your evening chai.",
                'price' => 140, 'weight' => '200g', 'tag' => 'Savoury Bite',
                'image' => 'images/products/jeera-cookies.jpg', 'color' => '#c8962e', 'sort_order' => 38,
            ],
            [
                'name' => 'Coconut Cookies',
                'category' => 'Cookies',
                'description' => "Crisp cookies packed with desiccated coconut for a fragrant bite in every piece.",
                'price' => 150, 'weight' => '200g', 'tag' => 'Fresh Coconut',
                'image' => 'images/products/coconut-cookies.jpg', 'color' => '#d4a940', 'sort_order' => 39,
            ],
            [
                'name' => 'Almond Cookies',
                'category' => 'Cookies',
                'description' => "Buttery cookies generously studded with real almond pieces — a little crunch in every bite.",
                'price' => 180, 'weight' => '200g', 'tag' => 'Loaded with Almonds',
                'image' => 'images/products/almond-cookies.jpg', 'color' => '#8a1c2b', 'sort_order' => 40,
            ],
            [
                'name' => 'Cashew Cookies',
                'category' => 'Cookies',
                'description' => "Shortbread-style cookies packed with roasted cashew bits, baked till golden and delicately crumbly.",
                'price' => 190, 'weight' => '200g', 'tag' => 'Rich & Nutty',
                'image' => 'images/products/cashew-cookies.jpg', 'color' => '#c1440e', 'sort_order' => 41,
            ],
            [
                'name' => 'Chocolate Chip Cookies',
                'category' => 'Cookies',
                'description' => "Classic chocolate chip cookies, baked soft in the centre and just crisp at the edges — a favourite with the little ones.",
                'price' => 170, 'weight' => '200g', 'tag' => "Kids' Favourite",
                'image' => 'images/products/choco-chip-cookies.jpg', 'color' => '#a97a1f', 'sort_order' => 42,
            ],
            [
                'name' => 'Atta Cookies',
                'category' => 'Cookies',
                'description' => "Made with whole wheat flour and just enough jaggery for a lightly sweet, wholesome everyday cookie.",
                'price' => 140, 'weight' => '200g', 'tag' => 'Whole Wheat',
                'image' => 'images/products/multigrain-cookies.jpg', 'color' => '#6b4423', 'sort_order' => 43,
            ],
            [
                'name' => 'Multigrain Cookies',
                'category' => 'Cookies',
                'description' => "A blend of oats, ragi and wheat baked into a crisp, better-for-you cookie that doesn't skimp on flavour.",
                'price' => 160, 'weight' => '200g', 'tag' => 'Health Bite',
                'image' => 'images/products/multigrain-cookies.jpg', 'color' => '#c8962e', 'sort_order' => 44,
            ],
            [
                'name' => 'Karachi Biscuit',
                'category' => 'Cookies',
                'description' => "Buttery shortbread studded with colourful tutti-frutti — a nostalgic bakery favourite loved across generations.",
                'price' => 200, 'weight' => '250g', 'tag' => 'Tutti Frutti',
                'image' => 'images/products/karachi-biscuit.jpg', 'color' => '#d4a940', 'sort_order' => 45,
            ],

            // Mathi
            [
                'name' => 'Methi Mathri',
                'category' => 'Mathi',
                'description' => "Flaky, savoury discs flavoured with fresh fenugreek leaves — deep-fried till crisp and golden.",
                'price' => 120, 'weight' => '200g', 'tag' => 'Fenugreek Flavour',
                'image' => 'images/products/methi-mathri.jpg', 'color' => '#c1440e', 'sort_order' => 46,
            ],
            [
                'name' => 'Ajwain Mathri',
                'category' => 'Mathi',
                'description' => "Classic flaky mathri spiced with carom seeds (ajwain) — light on the stomach and perfect with pickle or chai.",
                'price' => 110, 'weight' => '200g', 'tag' => 'Digestive Spice',
                'image' => 'images/products/punjabi-mathri.jpg', 'color' => '#a97a1f', 'sort_order' => 47,
            ],
            [
                'name' => 'Sweet Mathri (Shakarpara)',
                'category' => 'Mathi',
                'description' => "Crisp, diamond-cut pastry pieces coated in a delicate sugar glaze — a sweet counterpart to our savoury mathris.",
                'price' => 130, 'weight' => '250g', 'tag' => 'Sugar Coated',
                'image' => 'images/products/sweet-mathri.jpg', 'color' => '#8a1c2b', 'sort_order' => 48,
            ],
            [
                'name' => 'Punjabi Mathri',
                'category' => 'Mathi',
                'description' => "Thick, layered mathri made the Punjabi way — extra flaky, extra filling, and built to last through the week.",
                'price' => 120, 'weight' => '250g', 'tag' => 'Thick & Flaky',
                'image' => 'images/products/punjabi-mathri.jpg', 'color' => '#c8962e', 'sort_order' => 49,
            ],
            [
                'name' => 'Rajasthani Mathri',
                'category' => 'Mathi',
                'description' => "A Rajasthani take on mathri, spiced generously and fried to a deep golden crunch — a household staple across the desert state.",
                'price' => 125, 'weight' => '200g', 'tag' => 'Desert Recipe',
                'image' => 'images/products/methi-mathri.jpg', 'color' => '#d4a940', 'sort_order' => 50,
            ],
            [
                'name' => 'Suji Mathri',
                'category' => 'Mathi',
                'description' => "Semolina worked into the dough for an extra-crisp, slightly grainy bite that holds its crunch for weeks.",
                'price' => 115, 'weight' => '200g', 'tag' => 'Semolina Crunch',
                'image' => 'images/products/sweet-mathri.jpg', 'color' => '#7a1622', 'sort_order' => 51,
            ],
            [
                'name' => 'Namkeen Mathri',
                'category' => 'Mathi',
                'description' => "Our everyday savoury mathri — simple, salted, and endlessly snackable straight from the jar.",
                'price' => 120, 'weight' => '250g', 'tag' => 'Everyday Snack',
                'image' => 'images/products/punjabi-mathri.jpg', 'color' => '#c1440e', 'sort_order' => 52,
            ],
            [
                'name' => 'Palak Mathri',
                'category' => 'Mathi',
                'description' => "Pureed spinach worked into the dough for a subtly earthy flavour and a lovely pale green tint.",
                'price' => 130, 'weight' => '200g', 'tag' => 'Spinach Twist',
                'image' => 'images/products/methi-mathri.jpg', 'color' => '#a97a1f', 'sort_order' => 53,
            ],
            [
                'name' => 'Masala Mathri',
                'category' => 'Mathi',
                'description' => "A spicier mathri loaded with red chilli and garam masala for those who like their snacks with a kick.",
                'price' => 125, 'weight' => '200g', 'tag' => 'Extra Spiced',
                'image' => 'images/products/sweet-mathri.jpg', 'color' => '#8a1c2b', 'sort_order' => 54,
            ],
            [
                'name' => 'Khasta Mathri',
                'category' => 'Mathi',
                'description' => "Our flakiest mathri yet — layered generously with ghee before frying for a texture that shatters with every bite.",
                'price' => 120, 'weight' => '250g', 'tag' => 'Extra Flaky',
                'image' => 'images/products/punjabi-mathri.jpg', 'color' => '#c8962e', 'sort_order' => 55,
            ],

            // Dry Fruits
            [
                'name' => 'Premium Cashew (Kaju)',
                'category' => 'Dry Fruits',
                'description' => "Large, whole cashews, hand-sorted for size and freshness. Rich, buttery, and perfect for gifting or snacking.",
                'price' => 550, 'weight' => '250g', 'tag' => 'Whole & Grade A',
                'image' => 'images/products/cashew-pack.jpg', 'color' => '#6b4423', 'sort_order' => 56,
            ],
            [
                'name' => 'California Almonds (Badam)',
                'category' => 'Dry Fruits',
                'description' => "Plump, fresh California almonds — a wholesome daily snack packed with good fats and crunch.",
                'price' => 480, 'weight' => '250g', 'tag' => 'Protein Rich',
                'image' => 'images/products/almond-pack.jpg', 'color' => '#3d7a52', 'sort_order' => 57,
            ],
            [
                'name' => 'Premium Pistachios (Pista)',
                'category' => 'Dry Fruits',
                'description' => "Lightly roasted and salted pistachios with a satisfying crack — one of our most-gifted dry fruit packs.",
                'price' => 650, 'weight' => '250g', 'tag' => 'Roasted & Salted',
                'image' => 'images/products/pista-pack.jpg', 'color' => '#5c9468', 'sort_order' => 58,
            ],
            [
                'name' => 'Seedless Raisins (Kishmish)',
                'category' => 'Dry Fruits',
                'description' => "Plump, seedless raisins with a natural sweetness — great for snacking, baking, or topping your kheer.",
                'price' => 220, 'weight' => '250g', 'tag' => 'Naturally Sweet',
                'image' => 'images/products/raisins-pack.jpg', 'color' => '#8a1c2b', 'sort_order' => 59,
            ],
            [
                'name' => 'Kashmiri Walnuts (Akhrot)',
                'category' => 'Dry Fruits',
                'description' => "Fresh, light-coloured walnut kernels from Kashmir — mild, buttery, and perfect for a heart-healthy snack.",
                'price' => 500, 'weight' => '250g', 'tag' => 'Fresh Kernels',
                'image' => 'images/products/walnut-pack.jpg', 'color' => '#a97a1f', 'sort_order' => 60,
            ],
            [
                'name' => 'Dried Figs (Anjeer)',
                'category' => 'Dry Fruits',
                'description' => "Soft, naturally sweet dried figs — a wholesome snack or a lovely addition to your morning oats.",
                'price' => 420, 'weight' => '250g', 'tag' => 'Soft & Chewy',
                'image' => 'images/products/fig-pack.jpg', 'color' => '#6b4423', 'sort_order' => 61,
            ],
            [
                'name' => 'Premium Dates (Khajoor)',
                'category' => 'Dry Fruits',
                'description' => "Soft, seedless dates with a rich caramel sweetness — a healthier way to satisfy any sugar craving.",
                'price' => 350, 'weight' => '500g', 'tag' => 'Soft & Seedless',
                'image' => 'images/products/dates-pack.jpg', 'color' => '#3d7a52', 'sort_order' => 62,
            ],
            [
                'name' => 'Pine Nuts (Chilgoza)',
                'category' => 'Dry Fruits',
                'description' => "Delicate, buttery pine nuts sourced from the Himalayan pine forests — a rare treat in every handful.",
                'price' => 600, 'weight' => '100g', 'tag' => 'Rare & Roasted',
                'image' => 'images/products/pinenuts-pack.jpg', 'color' => '#5c9468', 'sort_order' => 63,
            ],
            [
                'name' => 'Mixed Dry Fruit Box',
                'category' => 'Dry Fruits',
                'description' => "A generous assortment of cashews, almonds, pistachios and raisins packed in a gift-ready box — perfect for any occasion.",
                'price' => 700, 'weight' => '500g', 'tag' => 'Gift Box',
                'image' => 'images/products/cashew-pack.jpg', 'color' => '#8a1c2b', 'sort_order' => 64,
            ],
            [
                'name' => 'Dry Fruit Chikki',
                'category' => 'Dry Fruits',
                'description' => "Roasted nuts set in a thin layer of jaggery brittle — crunchy, wholesome, and naturally sweetened.",
                'price' => 280, 'weight' => '250g', 'tag' => 'Jaggery Sweetened',
                'image' => 'images/products/dryfruit-chikki.jpg', 'color' => '#a97a1f', 'sort_order' => 65,
            ],

            // Syrup
            [
                'name' => 'Jalebi',
                'category' => 'Syrup',
                'description' => "Crisp, syrup-soaked spirals fried fresh to order — best enjoyed warm, the way Thuthibari has always loved it.",
                'price' => 150, 'weight' => '250g', 'tag' => 'Fresh & Hot',
                'image' => 'images/products/jalebi-2.jpg', 'color' => '#c1440e', 'sort_order' => 66,
            ],
            [
                'name' => 'Imarti',
                'category' => 'Syrup',
                'description' => "A flower-shaped cousin of jalebi, made from urad dal batter and soaked in saffron-scented syrup.",
                'price' => 160, 'weight' => '250g', 'tag' => 'Urad Dal Special',
                'image' => 'images/products/imarti.jpg', 'color' => '#7a1622', 'sort_order' => 67,
            ],
            [
                'name' => 'Chhena Jalebi',
                'category' => 'Syrup',
                'description' => "A softer, chhena-based take on classic jalebi — spongy inside, syrup-soaked outside.",
                'price' => 180, 'weight' => '6 pcs', 'tag' => 'Bengali Style',
                'image' => 'images/products/chhena-jalebi.jpg', 'color' => '#a97a1f', 'sort_order' => 68,
            ],
            [
                'name' => 'Balushahi',
                'category' => 'Syrup',
                'description' => "Flaky, doughnut-like discs deep-fried and dipped in sugar syrup for a crisp, glazed shell and soft centre.",
                'price' => 170, 'weight' => '6 pcs', 'tag' => 'Flaky & Glazed',
                'image' => 'images/products/balushahi.jpg', 'color' => '#d4a940', 'sort_order' => 69,
            ],
            [
                'name' => 'Shakkarpara',
                'category' => 'Syrup',
                'description' => "Crisp, syrup-glazed pastry diamonds — a simple, sweet snack that keeps well for weeks.",
                'price' => 140, 'weight' => '250g', 'tag' => 'Sugar Glazed',
                'image' => 'images/products/shakkarpara.jpg', 'color' => '#c1440e', 'sort_order' => 70,
            ],
            [
                'name' => 'Rasmalai',
                'category' => 'Syrup',
                'description' => "Soft chhena discs soaked in thickened, saffron-cardamom milk. Served chilled, it's silky in every spoonful.",
                'price' => 220, 'weight' => '6 pcs', 'tag' => 'Creamy & Chilled',
                'image' => 'images/products/rasmalai.jpg', 'color' => '#7a1622', 'sort_order' => 71,
            ],
            [
                'name' => 'Kalajamun',
                'category' => 'Syrup',
                'description' => "A darker, richer cousin of gulab jamun — fried longer for a deep caramel colour and toffee-like edge.",
                'price' => 190, 'weight' => '6 pcs', 'tag' => 'Dark & Rich',
                'image' => 'images/products/kalajamun.jpg', 'color' => '#a97a1f', 'sort_order' => 72,
            ],
            [
                'name' => 'Malpua',
                'category' => 'Syrup',
                'description' => "Sweet, syrup-soaked pancakes fried till the edges turn crisp — a festive favourite, best served warm.",
                'price' => 200, 'weight' => '6 pcs', 'tag' => 'Pancake Sweet',
                'image' => 'images/products/malpua.jpg', 'color' => '#d4a940', 'sort_order' => 73,
            ],
            [
                'name' => 'Ghevar',
                'category' => 'Syrup',
                'description' => "A honeycomb-textured disc soaked in syrup and topped with rabri and nuts — a Rajasthani festival specialty.",
                'price' => 280, 'weight' => '300g', 'tag' => 'Rajasthani Special',
                'image' => 'images/products/ghevar.jpg', 'color' => '#c1440e', 'sort_order' => 74,
            ],
            [
                'name' => 'Rabri Jalebi Combo',
                'category' => 'Syrup',
                'description' => "Hot, crisp jalebis served over a bed of chilled, thickened rabri — the ultimate combination of textures and temperatures.",
                'price' => 280, 'weight' => '400g', 'tag' => 'Combo Special',
                'image' => 'images/products/rabri-jalebi.jpg', 'color' => '#7a1622', 'sort_order' => 75,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['name' => $product['name']], $product);
        }
    }
}
